### ISSUE TITLE
[prismic-cli@3.8.0-beta.0 & prismic-cli@3.8.0-alpha.3] Error: Cannot find module '../common/Frameworks'

### ISSUE THREAD

**Issue by tobimori** [prismicio/prismic-cli#53]
Any command throws the following error.

```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module '../common/Frameworks'
Require stack:
- /home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/slicemachine/commands/pull.js
- /home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/slicemachine/commands/index.js
- /home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/slicemachine/index.js
- /home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/index.js
- /home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/prismic.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/slicemachine/commands/pull.js:57:42)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/slicemachine/commands/pull.js',
    '/home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/slicemachine/commands/index.js',
    '/home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/slicemachine/index.js',
    '/home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/commands/index.js',
    '/home/tobimori/.nvm/versions/node/v12.17.0/lib/node_modules/prismic-cli/bin/prismic.js'
  ]
}

**Comment by tobimori** [comment]
@jrah had the same issue in #48

**Comment by phillysnow** [comment]
Hi @tobimori ,

If you can try doing a pull on the latest beta of the CLI this should be resolved.
